# Site settings
url: http://manhtai.com
title: Mạnh Tài
author: Mạnh Tài
description: "Thống kê, R và những thứ khác."
permalink: /:categories/:title/

# Build settings
markdown: kramdown
exclude:
 - unicorn.rb
 - README.md
 - Procfile
 - Gemfile
 - Gemfile.lock
 - config.ru
 - vendor
 - app.json

gallery:
  # path to the gallery
  dir: photos
  # title for gallery index
  title: "Phòng ảnh"
  # title prefix for gallery page. title=title_prefix+gallery_name
  title_prefix: "An-bom: "
  # field to control sorting of galleries for the index page
  # (possible values are: title, date_time, best_image)
  sort_field: "date_time"
  # sizes for thumbnails
  thumbnail_size:
    x: 400
    y: 400
  # custom configuration for individual gallery
  # best_image is image for the index page (defaults to last image)
  galleries:
  #  chile_trip:
  #    best_image: IMG_1068.JPG
  #  japan_trip:
  #    best_image: IMG_0690.JPG
  #  best:
  #    best_image: snaileo_gonzales.jpg
